### ISSUE TITLE
the running result using the attached data file is 0...

### ISSUE THREAD

**Issue by datouniao** [nerajbobra/embedded_pedometer#2]
The SDE is Dev C++ on windows 7...

**Comment by nerajbobra** [comment]
@datouniao, I wrote the code in C, using XCode. There is no requirement to use C++ or Windows. I have no issues running with the attached data file and get the following output: 
num steps: 21

Nobody else has mentioned any issues either. Not sure why it's not working for you, but I'd recommend checking the filepath of the data file on line 15 and making sure you changed it appropriately.
