### ISSUE TITLE
Coordinate axis and values of sample data

### ISSUE THREAD

**Issue by patilnabhi** [nerajbobra/embedded_pedometer#3]
(1) While looking at the sample data, are the values normalized? Shouldn't one of the axis values be close to gravitation acceleration?
(2) What is the coordinate axis of the accelerometer with which the sample data was collected?
(3) How many steps were actually walked vs. detected using the algorithm?

Thanks!

**Comment by nerajbobra** [comment]
Hi Abhishek, good questions
1 and 2. Unfortunately, I don't have that information. Looking at periods without motion, however, the Y axis has a 1g acceleration while the X and Z axes are approximately zero. So my intuition is that the accelerometer was oriented such that the Y axis corresponds to being horizontal, and that there is no normalization here.
3. There should be approximately 20 steps in this segment of data. The algorithm output is 21 steps.
