### ISSUE TITLE
Visual chart for the data

### ISSUE THREAD

**Issue by BestMafen** [nerajbobra/embedded_pedometer#6]
Hi, this algorithm looks like great, so I want to use it on our wearable watch product. Now I should run the algorithm by Python to show visual chart, but I am not sure the Python code I write is correctly, so can you attach the visual chart for the data you provide in the csv file?

**Comment by nerajbobra** [comment]
Hi, when you say visual chart, do you mean you want to see the individual outputs for each 4 second block? Here are the outputs:
num steps: 0
num steps: 6
num steps: 7
num steps: 8
num steps: 0
